### ISSUE TITLE
Possibility of using a ENV Variable to point fine to the denoiser folder?

### ISSUE THREAD

**Issue by RicardoMusch** [ChristopheMoreau/FiNE#1]
If there a possibility to point fine to the denoiser folder with a Env Variable?
Because it may not always be possible to easily put the denoise folder on the c drive.

**Comment by ChristopheMoreau** [comment]
Hi Ricardo, for sure. I'll do that asap. 
Cheer, Christophe

**Comment by RicardoMusch** [comment]
Awesome! 👍

**Comment by ChristopheMoreau** [comment]
Hi Ricardo, new version v3.30 is available for testing :)
Cheers.
Christophe
